#!/bin/bash

LCPATH=~/leetcode
cd $LCPATH

#create a directory given a problem name/number
PROBLEM_NUMBER=$1
if [[ $# -eq 0 ]] ; then
    echo 'Enter file name'
    exit 0
fi
rm -rf $LCPATH/$PROBLEM_NUMBER
mkdir $LCPATH/$PROBLEM_NUMBER

#insert template in the directory
cp $LCPATH/lc-template/main.go $LCPATH/$PROBLEM_NUMBER/
cp $LCPATH/lc-template/input.txt $LCPATH/$PROBLEM_NUMBER/
cd $PROBLEM_NUMBER

#create a mod file
go mod init $PROBLEM_NUMBER
